Add download option to skip accession numbers
jadchaar/sec-edgar-downloader pull request #142
Opened 2024-05-17 18:59 UTC by spolcyn

This improves download efficiency when some filings have been already downloaded to another location, such as when doing incremental updates.

The existing logic to skip already downloaded files when they are in the same `download_folder` is useful for local-only use, but is less useful when files are only local for a brief period before being sent to long-term storage.

2024-05-17 19:07 UTC, spolcyn commented
@jadchaar This feature has been manually tested -- would love a quick sanity check that this feature is reasonable to add and that I didn't miss it somewhere. Then will add automated tests.

2024-05-27 06:24 UTC, jadchaar requested changes
Thanks for the contribution! Left some feedback and ran the test suite against your changes

2024-05-27 06:24 UTC, jadchaar commented on sec_edgar_downloader/_Downloader.py
> +        skip_accession_numbers: Optional[set[str]] = None,
Please use Set from typing library here :)

2024-05-27 06:24 UTC, jadchaar commented on sec_edgar_downloader/_Downloader.py
> +                skip_accession_numbers=skip_accession_numbers,
This makes it seem like the value is a boolean, maybe rename to something like `accession_numbers_to_skip`

2024-05-27 06:24 UTC, jadchaar commented on sec_edgar_downloader/_Downloader.py
> +        skip_accession_numbers: Optional[set[str]] = None,
IMHO we should not expose this as a parameter, but instead automatically use the existing file system to determine which items to skip. 

Thoughts?

2024-06-20 16:45 UTC, spolcyn commented
I have applied the suggestions and added a test. Let me know if there are any outstanding issues!

2024-07-25 19:14 UTC, spolcyn commented
@jadchaar Any further issues or clarifications with this PR?

2024-07-26 04:48 UTC, jadchaar commented
Thanks again for the contribution @spolcyn. LGTM!

2024-07-26 04:48 UTC, jadchaar approved these changes
LGTM! Ship it!

2024-07-26 04:49 UTC, merged

2025-02-13 02:05 UTC, Elijas commented
@jadchaar This hasn't been uploaded to pypi

The latest version is 5.0.2 which was released at 2023-10-08


## Proof

<details>
  <summary>Source</summary>
  
```python
import requests
import zipfile
import tarfile
import io

def search_in_package(package: str, version: str, search_string: str) -> None:
    # Get package JSON metadata
    url = f"https://pypi.org/pypi/{package}/{version}/json"
    response = requests.get(url)
    data = response.json()

    # Find a suitable file to download (prefer wheel over sdist)
    download_url = None
    for file_info in data.get("urls", []):
        if file_info.get("packagetype") == "bdist_wheel":
            download_url = file_info.get("url")
            break
    if not download_url:
        # fallback to source distribution if wheel not found
        for file_info in data.get("urls", []):
            if file_info.get("packagetype") == "sdist":
                download_url = file_info.get("url")
                break

    if not download_url:
        raise ValueError("No downloadable file found for the package version.")

    print("Downloading from:", download_url)
    r = requests.get(download_url)
    r.raise_for_status()

    found = False

    # Helper function to search content for the target string
    def search_content(content, filename):
        nonlocal found
        if search_string in content:
            print(f"Found '{search_string}' in file: {filename}")
            found = True

    # Process wheel files (zip archives)
    if download_url.endswith(".whl"):
        with zipfile.ZipFile(io.BytesIO(r.content)) as z:
            for name in z.namelist():
                try:
                    with z.open(name) as f:
                        content = f.read().decode("utf-8", errors="ignore")
                        search_content(content, name)
                except Exception as e:
                    # If a file can’t be read as text, skip it
                    continue

    # Process source distributions (tar.gz archives)
    elif download_url.endswith((".tar.gz", ".tgz")):
        with tarfile.open(fileobj=io.BytesIO(r.content), mode="r:gz") as tar:
            for member in tar.getmembers():
                if member.isfile():
                    try:
                        f = tar.extractfile(member)
                        if f:
                            content = f.read().decode("utf-8", errors="ignore")
                            search_content(content, member.name)
                    except Exception as e:
                        continue
    else:
        print("Unknown file format.")

    if not found:
        print(f"'{search_string}' was not found in any file.")
  ```
  
</details>

https://github.com/jadchaar/sec-edgar-downloader/blob/15ebd0d538cd28145dffc87b5b6b88bcc579b655/sec_edgar_downloader/_Downloader.py#L69

```python
search = "download_details: bool = False"
search_in_package("sec-edgar-downloader", "5.0.2", search)
```
```
Found 'download_details: bool = False' in file: sec_edgar_downloader/_Downloader.py
Found 'download_details: bool = False' in file: sec_edgar_downloader/_types.py
```

https://github.com/jadchaar/sec-edgar-downloader/blob/15ebd0d538cd28145dffc87b5b6b88bcc579b655/sec_edgar_downloader/_Downloader.py#L70

```python
search = "accession_numbers_to_skip"
search_in_package("sec-edgar-downloader", "5.0.2", search)
```
```
'accession_numbers_to_skip' was not found in any file.
```

Related https://github.com/jadchaar/sec-edgar-downloader/issues/146

2025-02-14 05:59 UTC, jadchaar commented
Ah thanks @Elijas, I will publish it shortly!